/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */
export { OpenApiClient } from './OpenApiClient';

export { ApiError } from './core/ApiError';
export { BaseHttpRequest } from './core/BaseHttpRequest';
export { CancelablePromise, CancelError } from './core/CancelablePromise';
export { OpenAPI } from './core/OpenAPI';
export type { OpenAPIConfig } from './core/OpenAPI';

export type { AdditionalFunction } from './models/AdditionalFunction';
export type { AppKey } from './models/AppKey';
export type { BeginTransactionRequest } from './models/BeginTransactionRequest';
export type { BeginTransactionResponse } from './models/BeginTransactionResponse';
export type { BranchInfo } from './models/BranchInfo';
export type { BranchMetadata } from './models/BranchMetadata';
export type { BuildCollectionIndexRequest } from './models/BuildCollectionIndexRequest';
export type { BuildCollectionIndexResponse } from './models/BuildCollectionIndexResponse';
export type { CacheMetadata } from './models/CacheMetadata';
export type { ChannelMetadata } from './models/ChannelMetadata';
export type { Charge } from './models/Charge';
export type { ChargeTier } from './models/ChargeTier';
export type { Collation } from './models/Collation';
export type { CollectionDescription } from './models/CollectionDescription';
export type { CollectionIndex } from './models/CollectionIndex';
export type { CollectionInfo } from './models/CollectionInfo';
export type { CollectionMetadata } from './models/CollectionMetadata';
export type { CollectionOptions } from './models/CollectionOptions';
export type { CommitTransactionRequest } from './models/CommitTransactionRequest';
export type { CommitTransactionResponse } from './models/CommitTransactionResponse';
export type { CountRequest } from './models/CountRequest';
export type { CountResponse } from './models/CountResponse';
export type { CreateAppKeyRequest } from './models/CreateAppKeyRequest';
export type { CreateAppKeyResponse } from './models/CreateAppKeyResponse';
export type { CreateBranchRequest } from './models/CreateBranchRequest';
export type { CreateBranchResponse } from './models/CreateBranchResponse';
export type { CreateByIdRequest } from './models/CreateByIdRequest';
export type { CreateByIdResponse } from './models/CreateByIdResponse';
export type { CreateCacheOptions } from './models/CreateCacheOptions';
export type { CreateCacheRequest } from './models/CreateCacheRequest';
export type { CreateCacheResponse } from './models/CreateCacheResponse';
export type { CreateDocumentRequest } from './models/CreateDocumentRequest';
export type { CreateDocumentResponse } from './models/CreateDocumentResponse';
export type { CreateInvitationsRequest } from './models/CreateInvitationsRequest';
export type { CreateInvitationsResponse } from './models/CreateInvitationsResponse';
export type { CreateNamespaceRequest } from './models/CreateNamespaceRequest';
export type { CreateNamespaceResponse } from './models/CreateNamespaceResponse';
export type { CreateOrReplaceDocumentRequest } from './models/CreateOrReplaceDocumentRequest';
export type { CreateOrReplaceDocumentResponse } from './models/CreateOrReplaceDocumentResponse';
export type { CreateOrUpdateCollectionRequest } from './models/CreateOrUpdateCollectionRequest';
export type { CreateOrUpdateCollectionResponse } from './models/CreateOrUpdateCollectionResponse';
export type { CreateOrUpdateIndexRequest } from './models/CreateOrUpdateIndexRequest';
export type { CreateOrUpdateIndexResponse } from './models/CreateOrUpdateIndexResponse';
export type { CreateProjectRequest } from './models/CreateProjectRequest';
export type { CreateProjectResponse } from './models/CreateProjectResponse';
export type { DatabaseMetadata } from './models/DatabaseMetadata';
export type { DataPoint } from './models/DataPoint';
export type { DeleteAppKeyRequest } from './models/DeleteAppKeyRequest';
export type { DeleteAppKeyResponse } from './models/DeleteAppKeyResponse';
export type { DeleteBranchRequest } from './models/DeleteBranchRequest';
export type { DeleteBranchResponse } from './models/DeleteBranchResponse';
export type { DeleteByQueryRequest } from './models/DeleteByQueryRequest';
export type { DeleteByQueryResponse } from './models/DeleteByQueryResponse';
export type { DeleteCacheRequest } from './models/DeleteCacheRequest';
export type { DeleteCacheResponse } from './models/DeleteCacheResponse';
export type { DeleteDocumentRequest } from './models/DeleteDocumentRequest';
export type { DeleteDocumentResponse } from './models/DeleteDocumentResponse';
export type { DeleteIndexRequest } from './models/DeleteIndexRequest';
export type { DeleteIndexResponse } from './models/DeleteIndexResponse';
export type { DeleteInvitationsRequest } from './models/DeleteInvitationsRequest';
export type { DeleteInvitationsResponse } from './models/DeleteInvitationsResponse';
export type { DeleteNamespaceResponse } from './models/DeleteNamespaceResponse';
export type { DeleteProjectRequest } from './models/DeleteProjectRequest';
export type { DeleteProjectResponse } from './models/DeleteProjectResponse';
export type { DeleteRequest } from './models/DeleteRequest';
export type { DeleteRequestOptions } from './models/DeleteRequestOptions';
export type { DeleteResponse } from './models/DeleteResponse';
export type { DelRequest } from './models/DelRequest';
export type { DelResponse } from './models/DelResponse';
export type { DescribeCollectionRequest } from './models/DescribeCollectionRequest';
export type { DescribeCollectionResponse } from './models/DescribeCollectionResponse';
export type { DescribeDatabaseRequest } from './models/DescribeDatabaseRequest';
export type { DescribeDatabaseResponse } from './models/DescribeDatabaseResponse';
export type { DescribeNamespacesData } from './models/DescribeNamespacesData';
export type { DocStatus } from './models/DocStatus';
export type { DropCollectionRequest } from './models/DropCollectionRequest';
export type { DropCollectionResponse } from './models/DropCollectionResponse';
export type { Error } from './models/Error';
export type { ExplainResponse } from './models/ExplainResponse';
export type { FacetCount } from './models/FacetCount';
export type { FacetStats } from './models/FacetStats';
export type { Field } from './models/Field';
export type { GetAccessTokenRequest } from './models/GetAccessTokenRequest';
export type { GetAccessTokenResponse } from './models/GetAccessTokenResponse';
export type { GetDocumentResponse } from './models/GetDocumentResponse';
export type { GetIndexResponse } from './models/GetIndexResponse';
export type { GetInfoResponse } from './models/GetInfoResponse';
export type { GetNamespaceMetadataRequest } from './models/GetNamespaceMetadataRequest';
export type { GetNamespaceMetadataResponse } from './models/GetNamespaceMetadataResponse';
export type { GetResponse } from './models/GetResponse';
export type { GetRTChannelResponse } from './models/GetRTChannelResponse';
export type { GetRTChannelsResponse } from './models/GetRTChannelsResponse';
export type { GetSetRequest } from './models/GetSetRequest';
export type { GetSetResponse } from './models/GetSetResponse';
export type { GetUserMetadataRequest } from './models/GetUserMetadataRequest';
export type { GetUserMetadataResponse } from './models/GetUserMetadataResponse';
export type { GroupedSearchHits } from './models/GroupedSearchHits';
export type { HealthCheckResponse } from './models/HealthCheckResponse';
export type { ImportRequest } from './models/ImportRequest';
export type { ImportRequestOptions } from './models/ImportRequestOptions';
export type { ImportResponse } from './models/ImportResponse';
export type { IndexInfo } from './models/IndexInfo';
export type { InsertNamespaceMetadataRequest } from './models/InsertNamespaceMetadataRequest';
export type { InsertNamespaceMetadataResponse } from './models/InsertNamespaceMetadataResponse';
export type { InsertRequest } from './models/InsertRequest';
export type { InsertRequestOptions } from './models/InsertRequestOptions';
export type { InsertResponse } from './models/InsertResponse';
export type { InsertUserMetadataRequest } from './models/InsertUserMetadataRequest';
export type { InsertUserMetadataResponse } from './models/InsertUserMetadataResponse';
export type { Invitation } from './models/Invitation';
export type { InvitationInfo } from './models/InvitationInfo';
export type { Invoice } from './models/Invoice';
export type { InvoiceLineItem } from './models/InvoiceLineItem';
export type { KeysResponse } from './models/KeysResponse';
export type { ListAppKeysResponse } from './models/ListAppKeysResponse';
export type { ListBranchesResponse } from './models/ListBranchesResponse';
export type { ListCachesResponse } from './models/ListCachesResponse';
export type { ListCollectionsResponse } from './models/ListCollectionsResponse';
export type { ListIndexesResponse } from './models/ListIndexesResponse';
export type { ListInvitationsResponse } from './models/ListInvitationsResponse';
export type { ListInvoicesResponse } from './models/ListInvoicesResponse';
export type { ListNamespacesResponse } from './models/ListNamespacesResponse';
export type { ListProjectsResponse } from './models/ListProjectsResponse';
export type { ListSubscriptionResponse } from './models/ListSubscriptionResponse';
export type { ListUsersResponse } from './models/ListUsersResponse';
export type { Match } from './models/Match';
export type { MatchField } from './models/MatchField';
export type { Message } from './models/Message';
export type { MessagesRequest } from './models/MessagesRequest';
export type { MessagesResponse } from './models/MessagesResponse';
export type { MetricSeries } from './models/MetricSeries';
export type { NamespaceInfo } from './models/NamespaceInfo';
export type { Page } from './models/Page';
export type { PresenceResponse } from './models/PresenceResponse';
export type { ProjectInfo } from './models/ProjectInfo';
export type { ProjectMetadata } from './models/ProjectMetadata';
export type { QueryTimeSeriesMetricsRequest } from './models/QueryTimeSeriesMetricsRequest';
export type { QueryTimeSeriesMetricsResponse } from './models/QueryTimeSeriesMetricsResponse';
export type { QuotaLimitsRequest } from './models/QuotaLimitsRequest';
export type { QuotaLimitsResponse } from './models/QuotaLimitsResponse';
export type { QuotaUsageRequest } from './models/QuotaUsageRequest';
export type { QuotaUsageResponse } from './models/QuotaUsageResponse';
export type { ReadMessagesResponse } from './models/ReadMessagesResponse';
export type { ReadRequest } from './models/ReadRequest';
export type { ReadRequestOptions } from './models/ReadRequestOptions';
export type { ReadResponse } from './models/ReadResponse';
export type { ReplaceRequest } from './models/ReplaceRequest';
export type { ReplaceRequestOptions } from './models/ReplaceRequestOptions';
export type { ReplaceResponse } from './models/ReplaceResponse';
export type { ResponseMetadata } from './models/ResponseMetadata';
export type { RollbackTransactionRequest } from './models/RollbackTransactionRequest';
export type { RollbackTransactionResponse } from './models/RollbackTransactionResponse';
export type { RollupFunction } from './models/RollupFunction';
export type { RotateAppKeyRequest } from './models/RotateAppKeyRequest';
export type { RotateAppKeyResponse } from './models/RotateAppKeyResponse';
export type { SearchFacet } from './models/SearchFacet';
export type { SearchHit } from './models/SearchHit';
export type { SearchHitMeta } from './models/SearchHitMeta';
export type { SearchIndexRequest } from './models/SearchIndexRequest';
export type { SearchIndexResponse } from './models/SearchIndexResponse';
export type { SearchMetadata } from './models/SearchMetadata';
export type { SearchRequest } from './models/SearchRequest';
export type { SearchResponse } from './models/SearchResponse';
export type { SetRequest } from './models/SetRequest';
export type { SetResponse } from './models/SetResponse';
export type { Status } from './models/Status';
export type { StreamingReadResponse } from './models/StreamingReadResponse';
export type { StreamingSearchResponse } from './models/StreamingSearchResponse';
export type { TransactionCtx } from './models/TransactionCtx';
export type { TransactionOptions } from './models/TransactionOptions';
export type { UpdateAppKeyRequest } from './models/UpdateAppKeyRequest';
export type { UpdateAppKeyResponse } from './models/UpdateAppKeyResponse';
export type { UpdateDocumentRequest } from './models/UpdateDocumentRequest';
export type { UpdateDocumentResponse } from './models/UpdateDocumentResponse';
export type { UpdateNamespaceMetadataRequest } from './models/UpdateNamespaceMetadataRequest';
export type { UpdateNamespaceMetadataResponse } from './models/UpdateNamespaceMetadataResponse';
export type { UpdateRequest } from './models/UpdateRequest';
export type { UpdateRequestOptions } from './models/UpdateRequestOptions';
export type { UpdateResponse } from './models/UpdateResponse';
export type { UpdateUserMetadataRequest } from './models/UpdateUserMetadataRequest';
export type { UpdateUserMetadataResponse } from './models/UpdateUserMetadataResponse';
export type { User } from './models/User';
export type { VerifyInvitationRequest } from './models/VerifyInvitationRequest';
export type { VerifyInvitationResponse } from './models/VerifyInvitationResponse';
export type { WriteOptions } from './models/WriteOptions';

export { ApplicationKeysHttpService } from './services/ApplicationKeysHttpService';
export { AuthenticationHttpService } from './services/AuthenticationHttpService';
export { BillingHttpService } from './services/BillingHttpService';
export { CacheHttpService } from './services/CacheHttpService';
export { CollectionsHttpService } from './services/CollectionsHttpService';
export { DatabaseHttpService } from './services/DatabaseHttpService';
export { ManagementHttpService } from './services/ManagementHttpService';
export { ObservabilityHttpService } from './services/ObservabilityHttpService';
export { ProjectsHttpService } from './services/ProjectsHttpService';
export { RealtimeHttpService } from './services/RealtimeHttpService';
export { SearchHttpService } from './services/SearchHttpService';
