/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */

import type { ImportRequestOptions } from './ImportRequestOptions';

export type ImportRequest = {
    /**
     * Array of documents to import. Each document is a JSON object.
     */
    documents?: Array<Record<string, any>>;
    options?: ImportRequestOptions;
    /**
     * Optionally specify a database branch name to perform operation on
     */
    branch?: string;
    /**
     * Allow to create collection if it doesn't exists
     */
    create_collection?: boolean;
    /**
     * List of fields which constitutes primary key of the collection If not specified and field with name 'id' is present, it's used as a primary key, further if inferred type is UUID, then it's set as autogenerated.
     */
    primary_key?: Array<string>;
    /**
     * The list of autogenerated fields of the collection
     */
    autogenerated?: Array<string>;
};

